apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxweb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nginxweb
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nginxweb
    spec:
      containers:
      - name: nginxweb-container
        image: ekawafs/htmlcicd:40
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: nginxweb
  namespace: default
  labels:
    app: nginxweb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 31000
    protocol: TCP
  selector:
    app: nginxweb
