apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: htmleka
  name: htmleka
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: htmleka
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: htmleka
    spec:
      containers:
      - image: ekawafs/htmlcicd:35
        name: htmleka
        resources: {}
status: {}