apiVersion: v1
kind: Service
metadata:
  name: svc-flux
  namespace: default
  labels:
    app: flaskdemo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flaskdemo
